<?php
return array(
	array( // row #0
		'sitename' => 'Oficjalna strona Szkoły Podstawowej nr 9 w Legnicy',
		'siteurl' => 'www.sp9.legnica.pl/',
		'sitebanner' => '',
		'siteemail' => '',
		'siteusername' => 'Administrator',
		'siteintro' => '',
		'description' => 'Szkoła Podstawowa nr 9 w Legnicy, edukacja',
		'keywords' => 'sp9, sp9legnica, szkołapodstawowanr9wlegnicy, szkołapodstawowanr9legnica, szkołapodstawowa, legnicasp9wlegnicy, sp, 9, legnica, szkoła, podstawowa,sp 9, sp9, sp 9 legnica, sp9 legnica, szkoła podstawowa nr 9 w legnicy, szkoła podstawowa nr 9 legnica, szkoła podstawowa, legnica sp 9 w legnicy, sp9 w legnicy, szkoła podstawowa, legnica, biblioteka, samorząd uczniowski, plan lekcji, gazetka szkolna, wykaz podręczników, dziewiątka\r\n',
		'footer' => '<center>\r\n\r\nOFICJALNA STRONA SZKOŁY PODSTAWOWEJ NR 9 W LEGNICY<br>\r\n&#169; 2007 Webmaster: Renata Rewak. Wszelkie prawa zastrzeżone.<br>\r\n<a href=login.php>[loguj]</a>\r\n\r\n</center>',
		'opening_page' => 'news.php',
		'news_style' => 0,
		'locale' => 'Polish',
		'theme' => 'CeRNoBiL',
		'shortdate' => '%d/%m/%Y %H:%M',
		'longdate' => '%B %d %Y %H:%M:%S',
		'forumdate' => '%d-%m-%Y %H:%M',
		'subheaderdate' => '',
		'timeoffset' => '0',
		'numofthreads' => 5,
		'attachments' => 0,
		'attachmax' => 150000,
		'attachtypes' => '.gif,.jpg,.png,.zip,.rar,.tar',
		'thread_notify' => 0,
		'enable_registration' => 0,
		'email_verification' => 1,
		'admin_activation' => 1,
		'display_validation' => 1,
		'validation_method' => 'image',
		'thumb_w' => 100,
		'thumb_h' => 100,
		'photo_w' => 400,
		'photo_h' => 300,
		'photo_max_w' => 1800,
		'photo_max_h' => 1600,
		'photo_max_b' => 150000,
		'thumb_compression' => 'gd2',
		'thumbs_per_row' => 4,
		'thumbs_per_page' => 24,
		'tinymce_enabled' => 1,
		'smtp_host' => '',
		'smtp_username' => '',
		'smtp_password' => '',
		'bad_words_enabled' => 0,
		'bad_words' => '',
		'bad_word_replace' => '****',
		'guestposts' => 0,
		'numofshouts' => 10,
		'flood_interval' => 15,
		'counter' => 2418594,
		'version' => '6.01.6',
		'maintenance' => 0,
		'maintenance_message' => '',
	),
);
